version: "3.4"
services:
  leetcodees6:
    container_name: leetcodees6
    build:
      context: ../
      dockerfile: ./docker-compose/Dockerfile
    volumes:
      - ../:/leetcodees6
    command: |
      sh -c 'chmod u+x ./docker-compose/bin/wait-for && \
        # ./docker-compose/bin/wait-for redis:6379 -- \
        npm test && exit 0;'
